name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:

  build-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.203
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest

    - name: Install Observable dependencies
      run: dotnet restore ./src/MVx.Observable/MVx.Observable.csproj
    - name: Build Core
      run: dotnet build ./src/MVx.Observable/MVx.Observable.csproj --configuration Release --no-restore
    - name: Pack Core
      run: dotnet pack ./src/MVx.Observable/MVx.Observable.csproj -p:PackageVersion=5.0.$GITHUB_RUN_NUMBER --configuration Release -o nupkg --no-build
      
    - name: Install Monad dependencies
      run: dotnet restore ./src/MVx.Monads/MVx.Monads.csproj
    - name: Build Stream
      run: dotnet build ./src/MVx.Monads/MVx.Monads.csproj --configuration Release --no-restore
    - name: Pack Stream
      run: dotnet pack ./src/MVx.Monads/MVx.Monads.csproj -p:PackageVersion=5.0.$GITHUB_RUN_NUMBER --configuration Release -o nupkg --no-build

    - name: Push to GitHub Packages
      run: nuget push "nupkg/*.nupkg" -Source "https://nuget.pkg.github.com/ibebbs/index.json" -ApiKey ${{ secrets.GITHUB_TOKEN }}